import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Routes, Route, Link, NavLink, Navigate, Outlet, useNavigate, useParams} from 'react-router-dom';
import {CarFront, MapPin, CalendarDays, Users, ShieldCheck, Search, ArrowRight, CheckCircle2, XCircle, LogIn, UserPlus, LogOut, Menu, X, ChevronRight, Fuel, Settings2, Plus, Pencil, Power, Clock3, Route as RouteIcon, CircleDollarSign, Info, KeyRound, AlertCircle} from 'lucide-react';
import './styles.css';

const seedCars = [
 {id:'c1',name:'Toyota Corolla',category:'Compact',seats:5,price:39,transmission:'Automatic',fuel:'Hybrid',location:'Barcelona',available:true,description:'Reliable and efficient for city trips and weekend escapes.'},
 {id:'c2',name:'Volkswagen Golf',category:'Economy',seats:5,price:42,transmission:'Manual',fuel:'Petrol',location:'Barcelona',available:true,description:'A practical all-rounder with a comfortable cabin and easy handling.'},
 {id:'c3',name:'BMW 3 Series',category:'Premium',seats:5,price:79,transmission:'Automatic',fuel:'Petrol',location:'Barcelona',available:true,description:'Premium comfort, confident performance and plenty of space.'},
 {id:'c4',name:'Peugeot 3008',category:'SUV',seats:5,price:61,transmission:'Automatic',fuel:'Diesel',location:'Barcelona',available:true,description:'A spacious SUV for families, luggage and longer journeys.'},
 {id:'c5',name:'Renault Clio',category:'Economy',seats:5,price:34,transmission:'Manual',fuel:'Petrol',location:'Barcelona',available:false,description:'Compact, economical and ideal for urban driving.'},
 {id:'c6',name:'Tesla Model 3',category:'Premium',seats:5,price:89,transmission:'Automatic',fuel:'Electric',location:'Barcelona',available:true,description:'Quiet electric driving with modern technology and a long range.'}
];
const seedRides = [
 {id:'r1',origin:'Barcelona',destination:'Girona',date:'2026-10-10',time:'08:30',seats:3,price:12,driver:'Maria G.',status:'open'},
 {id:'r2',origin:'Barcelona',destination:'Tarragona',date:'2026-10-11',time:'09:00',seats:2,price:10,driver:'Carlos M.',status:'open'},
 {id:'r3',origin:'Girona',destination:'Barcelona',date:'2026-10-12',time:'18:15',seats:1,price:12,driver:'Laura P.',status:'open'},
 {id:'r4',origin:'Barcelona',destination:'Sitges',date:'2026-10-09',time:'17:30',seats:0,price:7,driver:'Jordi R.',status:'full'}
];
// Prototype-only demo credentials. A production backend must store salted password hashes, never plaintext.
const seedUsers = [
 {id:'u1',name:'Demo Customer',email:'demo@riderent.app',password:'demo123',role:'customer'},
 {id:'u2',name:'RideRent Admin',email:'admin@riderent.app',password:'admin123',role:'admin'}
];
function load(key, fallback){try{const x=JSON.parse(localStorage.getItem(key)); return x??fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function App(){
 const [cars,setCars]=useState(()=>load('rr_cars',seedCars)); const [rides,setRides]=useState(()=>load('rr_rides',seedRides)); const [users,setUsers]=useState(()=>load('rr_users',seedUsers)); const [session,setSession]=useState(()=>load('rr_session',null)); const [reservations,setReservations]=useState(()=>load('rr_reservations',[])); const [rideBookings,setRideBookings]=useState(()=>load('rr_rideBookings',[]));
 useEffect(()=>save('rr_cars',cars),[cars]); useEffect(()=>save('rr_rides',rides),[rides]); useEffect(()=>save('rr_users',users),[users]); useEffect(()=>save('rr_session',session),[session]); useEffect(()=>save('rr_reservations',reservations),[reservations]); useEffect(()=>save('rr_rideBookings',rideBookings),[rideBookings]);
 const login=(email,password)=>{const u=users.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password); if(!u)return {ok:false,message:'Incorrect email or password.'}; setSession({id:u.id,name:u.name,email:u.email,role:u.role}); return {ok:true,user:u}}
 const register=(name,email,password)=>{if(users.some(x=>x.email.toLowerCase()===email.toLowerCase()))return {ok:false,message:'This email is already in use.'}; if(!name||!email||password.length<6)return {ok:false,message:'Enter a name, valid email and password of at least 6 characters.'}; const u={id:'u'+Date.now(),name,email,password,role:'customer'}; setUsers([...users,u]); setSession({id:u.id,name:u.name,email:u.email,role:u.role}); return {ok:true,user:u}}
 const logout=()=>setSession(null)
 const reserve=(carId,start,end)=>{if(!session)return {ok:false,message:'Please log in first.'}; const car=cars.find(c=>c.id===carId); if(!car||!car.available)return {ok:false,message:'This vehicle is not available.'}; const exists=reservations.some(r=>r.carId===carId&&r.status==='active'&&!(end<=r.start||start>=r.end)); if(exists)return {ok:false,message:'Vehicle is unavailable for those dates.'}; const r={id:'b'+Date.now(),userId:session.id,carId,start,end,status:'active',createdAt:new Date().toISOString()}; setReservations([...reservations,r]); return {ok:true,reservation:r}}
 const cancelReservation=(id)=>setReservations(reservations.map(r=>r.id===id?{...r,status:'cancelled'}:r))
 const addRide=(ride)=>{const r={...ride,id:'r'+Date.now(),driver:session.name,status:'open'}; setRides([r,...rides]); return r}
 const joinRide=(id)=>{const ride=rides.find(r=>r.id===id); if(!ride||ride.seats<1)return {ok:false,message:'This ride is full.'}; if(rideBookings.some(b=>b.rideId===id&&b.userId===session.id))return {ok:false,message:'You have already joined this ride.'}; setRides(rides.map(r=>r.id===id?{...r,seats:r.seats-1,status:r.seats-1===0?'full':'open'}:r)); setRideBookings([...rideBookings,{id:'jb'+Date.now(),rideId:id,userId:session.id}]); return {ok:true}}
 const adminAddCar=(data)=>setCars([...cars,{...data,id:'c'+Date.now(),available:true,price:Number(data.price),seats:Number(data.seats)}]);
 const adminUpdateCar=(id,data)=>setCars(cars.map(c=>c.id===id?{...c,...data,price:Number(data.price),seats:Number(data.seats)}:c));
 const adminToggleCar=(id)=>setCars(cars.map(c=>c.id===id?{...c,available:!c.available}:c));
 return <Routes>
   <Route element={<Layout session={session} logout={logout}/>}>
    <Route path="/" element={<Home session={session} cars={cars} rides={rides}/>} />
    <Route path="/login" element={session?<Navigate to="/" replace/>:<LoginPage onLogin={login}/>} />
    <Route path="/register" element={session?<Navigate to="/" replace/>:<RegisterPage onRegister={register}/>} />
    <Route path="/cars" element={<Protected session={session}><CarsPage cars={cars}/></Protected>} />
    <Route path="/cars/:id" element={<Protected session={session}><CarDetails cars={cars} reserve={reserve}/></Protected>} />
    <Route path="/reservations" element={<Protected session={session}><ReservationsPage session={session} cars={cars} reservations={reservations} cancel={cancelReservation}/></Protected>} />
    <Route path="/rides" element={<Protected session={session}><RidesPage session={session} rides={rides} joinRide={joinRide} rideBookings={rideBookings}/></Protected>} />
    <Route path="/create-ride" element={<Protected session={session}><CreateRidePage addRide={addRide}/></Protected>} />
    <Route path="/admin" element={<AdminRoute session={session}><AdminPage cars={cars} addCar={adminAddCar} updateCar={adminUpdateCar} toggleCar={adminToggleCar}/></AdminRoute>} />
    <Route path="*" element={<Navigate to="/" replace/>}/>
   </Route>
 </Routes>
}
function Protected({session,children}){return session?children:<Navigate to="/login" replace/>}
function AdminRoute({session,children}){return session?.role==='admin'?children:<Navigate to="/" replace/>}
function Layout({session,logout}){const [open,setOpen]=useState(false); const nav=useNavigate(); const links=[['/','Home'],['/cars','Rent a car'],['/rides','Shared rides'],['/reservations','My reservations']]; return <div className="app-shell"><header className="header"><div className="container nav"><Link className="brand" to="/"><span className="brand-mark"><CarFront size={20}/></span>Ride<span>Rent</span></Link><button className="menu-btn" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'nav-links open':'nav-links'}>{links.map(([to,label])=><NavLink key={to} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'active':''} to={to}>{label}</NavLink>)}{session?.role==='admin'&&<NavLink to="/admin" onClick={()=>setOpen(false)}>Admin</NavLink>}{session?<button className="btn btn-ghost nav-auth" onClick={()=>{logout();nav('/')}}><LogOut size={16}/>Log out</button>:<Link className="btn btn-dark nav-auth" to="/login" onClick={()=>setOpen(false)}><LogIn size={16}/>Log in</Link>}</nav></div></header><main>{session&&<div className="session-bar"><div className="container session-inner"><span>Signed in as <strong>{session.name}</strong>{session.role==='admin'?' · Administrator':''}</span><Link to="/create-ride">Create a shared ride <ArrowRight size={15}/></Link></div></div>}{/* routes */}<OutletHack/></main><footer className="footer"><div className="container footer-grid"><div><div className="brand footer-brand"><span className="brand-mark"><CarFront size={18}/></span>Ride<span>Rent</span></div><p>One simple place to rent cars and share journeys.</p></div><div><b>Product</b><span>Car rental</span><span>Shared rides</span><span>Secure accounts</span></div><div><b>Project</b><span>React application</span><span>Responsive UI</span><span>Challenge 1</span></div></div><div className="container copyright">© 2026 RideRent · Prototype for DAM2 Projecte intermodular</div></footer></div>}
// React Router's Outlet is kept in a tiny component to make Layout compact.
function OutletHack(){return <Outlet/>}
function Home({session,cars,rides}){const featured=cars.filter(c=>c.available).slice(0,3); return <div><section className="hero"><div className="container hero-grid"><div><div className="eyebrow"><ShieldCheck size={15}/> Simple. Flexible. Secure.</div><h1>Rent a car.<br/><em>Share the road.</em></h1><p className="hero-copy">RideRent brings car rental and shared rides together, so your next journey starts in one place.</p><div className="hero-actions"><Link className="btn btn-primary btn-lg" to={session?'/cars':'/register'}>{session?'Find a car':'Get started'}<ArrowRight size={18}/></Link><Link className="btn btn-outline btn-lg" to={session?'/rides':'/login'}>Explore shared rides</Link></div><div className="hero-points"><span><CheckCircle2 size={16}/> No hidden fees in prototype</span><span><CheckCircle2 size={16}/> Mobile friendly</span></div></div><div className="hero-card"><div className="hero-car-shape"><div className="wheel w1"/><div className="wheel w2"/><div className="window-shape"/></div><div className="hero-card-content"><span>Featured today</span><strong>Toyota Corolla Hybrid</strong><small>From €39 / day · Barcelona</small></div></div></div></section><section className="container section"><div className="section-head"><div><div className="eyebrow">WHY RIDERENT</div><h2>Everything for your journey</h2></div><Link className="text-link" to={session?'/cars':'/register'}>View vehicles <ChevronRight size={17}/></Link></div><div className="feature-grid"><Feature icon={<CarFront/>} title="Easy car rental" text="Search, filter, inspect and reserve available vehicles."/><Feature icon={<Users/>} title="Shared journeys" text="Find a ride or create an offer for other customers."/><Feature icon={<ShieldCheck/>} title="Protected access" text="Personal bookings and ride management stay behind login."/></div></section><section className="section soft"><div className="container"><div className="section-head"><div><div className="eyebrow">AVAILABLE NOW</div><h2>Popular cars</h2></div><Link className="text-link" to={session?'/cars':'/register'}>See all <ChevronRight size={17}/></Link></div><div className="car-grid">{featured.map(c=><CarCard key={c.id} car={c}/>)}</div></div></section><section className="container cta"><div><div className="eyebrow">SHARE THE JOURNEY</div><h2>Have a spare seat?</h2><p>Create a shared ride and let other customers join your route.</p></div><Link className="btn btn-dark" to={session?'/create-ride':'/register'}>Create a ride <ArrowRight size={17}/></Link></section></div>}
function Feature({icon,title,text}){return <div className="feature-card"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function CarsPage({cars}){const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const [max,setMax]=useState(100); const results=cars.filter(c=>c.available&&(!query||`${c.name} ${c.location}`.toLowerCase().includes(query.toLowerCase()))&&(category==='All'||c.category===category)&&c.price<=max); return <div className="container page"><PageTitle eyebrow="CAR RENTAL" title="Find your next car" subtitle="Search by model, category or location and compare available vehicles."/><div className="search-panel"><label><Search size={18}/> <input aria-label="Search cars" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Toyota, SUV, Barcelona…"/></label><label><span>Category</span><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option><option>Economy</option><option>Compact</option><option>SUV</option><option>Premium</option></select></label><label><span>Max € / day</span><select value={max} onChange={e=>setMax(Number(e.target.value))}><option value="100">€100</option><option value="80">€80</option><option value="60">€60</option><option value="45">€45</option></select></label></div><div className="results-line"><strong>{results.length} vehicles</strong><span>Available for your search</span></div>{results.length?<div className="car-grid">{results.map(c=><CarCard key={c.id} car={c}/>)}</div>:<Empty icon={<Search/>} title="No vehicles found" text="Try changing your search or filters."/>}<div className="scope-note"><Info size={17}/><div><b>Prototype note</b><span>Payments are intentionally not included in Challenge 1. Reservations are simulated locally.</span></div></div></div>}
function CarCard({car}){return <article className="car-card"><div className={'car-visual '+car.category.toLowerCase()}><div className="car-mini"><span className="mini-window"/><span className="mini-wheel one"/><span className="mini-wheel two"/></div><span className="category-pill">{car.category}</span></div><div className="car-body"><div className="car-title"><div><h3>{car.name}</h3><span>{car.location}</span></div><strong>€{car.price}<small>/day</small></strong></div><div className="specs"><span><Users size={15}/>{car.seats} seats</span><span><Settings2 size={15}/>{car.transmission}</span><span><Fuel size={15}/>{car.fuel}</span></div><Link className="btn btn-outline full" to={'/cars/'+car.id}>View details <ArrowRight size={16}/></Link></div></article>}
function CarDetails({cars,reserve}){const {id}=useParams();const car=cars.find(c=>c.id===id);const [start,setStart]=useState('2026-10-10');const [end,setEnd]=useState('2026-10-12');const [msg,setMsg]=useState(null);if(!car)return <Navigate to="/cars" replace/>; const submit=e=>{e.preventDefault();if(start>=end){setMsg({type:'error',text:'End date must be after start date.'});return}const result=reserve(car.id,start,end);setMsg(result.ok?{type:'ok',text:'Reservation created successfully. View it in My reservations.'}:{type:'error',text:result.message});}; return <div className="container page"><Link className="back" to="/cars">← Back to cars</Link><div className="detail-grid"><div><div className={'detail-visual '+car.category.toLowerCase()}><div className="car-large"><span className="large-window"/><span className="large-wheel one"/><span className="large-wheel two"/></div><span className="category-pill">{car.category}</span></div><div className="detail-copy"><div className="eyebrow">{car.category.toUpperCase()} · {car.location.toUpperCase()}</div><h1>{car.name}</h1><p>{car.description}</p><div className="detail-specs"><div><Users/><b>{car.seats}</b><span>Seats</span></div><div><Settings2/><b>{car.transmission}</b><span>Transmission</span></div><div><Fuel/><b>{car.fuel}</b><span>Fuel</span></div><div><CheckCircle2/><b>{car.available?'Available':'Unavailable'}</b><span>Status</span></div></div></div></div><aside className="booking-card"><div><span className="muted">Daily rate</span><div className="price-big">€{car.price}<small>/day</small></div></div><form onSubmit={submit} className="form"><label>Pick-up date<input type="date" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>Return date<input type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></label>{msg&&<Alert type={msg.type} text={msg.text}/>}<button className="btn btn-primary full" disabled={!car.available}>{car.available?'Reserve vehicle':'Vehicle unavailable'} <ArrowRight size={16}/></button></form><small className="fine"><ShieldCheck size={14}/> Secure account required. No real payment is taken.</small></aside></div></div>}
function ReservationsPage({session,cars,reservations,cancel}){const mine=reservations.filter(r=>r.userId===session.id);return <div className="container page"><PageTitle eyebrow="MY ACCOUNT" title="My reservations" subtitle="Manage your current and previous rental bookings."/><div className="stats-row"><Stat n={mine.filter(r=>r.status==='active').length} label="Active"/><Stat n={mine.filter(r=>r.status==='cancelled').length} label="Cancelled"/><Stat n={mine.length} label="Total bookings"/></div>{mine.length?<div className="reservation-list">{mine.map(r=>{const c=cars.find(x=>x.id===r.carId);return <div className="reservation" key={r.id}><div className={'res-car '+c?.category.toLowerCase()}><div className="car-mini"><span className="mini-window"/><span className="mini-wheel one"/><span className="mini-wheel two"/></div></div><div className="res-main"><div><span className="eyebrow">BOOKING {r.id.slice(-5).toUpperCase()}</span><h3>{c?.name||'Vehicle'}</h3></div><div className="res-meta"><span><CalendarDays size={15}/>{r.start} → {r.end}</span><span><MapPin size={15}/>{c?.location}</span></div></div><div className="res-status"><span className={r.status==='active'?'status active':'status cancelled'}>{r.status==='active'?'Active':'Cancelled'}</span>{r.status==='active'&&<button className="btn btn-ghost danger" onClick={()=>cancel(r.id)}>Cancel</button>}</div></div>})}</div>:<Empty icon={<CalendarDays/>} title="No reservations yet" text="Choose a vehicle and your booking will appear here." action={<Link className="btn btn-dark" to="/cars">Find a car</Link>}/>}</div>}
function RidesPage({session,rides,joinRide,rideBookings}){const [origin,setOrigin]=useState('');const [destination,setDestination]=useState('');const [date,setDate]=useState('');const [notice,setNotice]=useState(null);const results=rides.filter(r=>(!origin||r.origin.toLowerCase().includes(origin.toLowerCase()))&&(!destination||r.destination.toLowerCase().includes(destination.toLowerCase()))&&(!date||r.date===date));const mine=rideBookings.filter(b=>b.userId===session.id);return <div className="container page"><PageTitle eyebrow="SHARED RIDES" title="Find a shared journey" subtitle="Search available rides or offer your own seat to other customers."/><div className="search-panel ride-search"><label><MapPin size={18}/><input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="From"/></label><label><RouteIcon size={18}/><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="To"/></label><label><CalendarDays size={18}/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><Link className="btn btn-dark" to="/create-ride"><Plus size={17}/> Offer a ride</Link></div>{notice&&<Alert type={notice.type} text={notice.text}/>}<div className="results-line"><strong>{results.length} rides</strong><span>Matching your search</span></div><div className="ride-list">{results.map(r=><article className="ride-card" key={r.id}><div className="ride-time"><span>{r.time}</span><small>{r.date}</small></div><div className="ride-route"><div><b>{r.origin}</b><span className="route-line"/><b>{r.destination}</b></div><small>Driver: {r.driver}</small></div><div className="ride-info"><span><Users size={15}/>{r.seats} seats left</span><strong>€{r.price}</strong></div><button className="btn btn-primary" disabled={r.seats===0||mine.some(b=>b.rideId===r.id)} onClick={()=>{const x=joinRide(r.id);setNotice(x.ok?{type:'ok',text:'You joined the ride successfully.'}:{type:'error',text:x.message})}}>{mine.some(b=>b.rideId===r.id)?'Joined':r.seats===0?'Full':'Join ride'}</button></article>)}{!results.length&&<Empty icon={<RouteIcon/>} title="No suitable rides" text="Try another route or date, or create your own ride."/>}</div></div>}
function CreateRidePage({addRide}){const nav=useNavigate();const [form,setForm]=useState({origin:'Barcelona',destination:'',date:'2026-10-10',time:'09:00',seats:2,price:10});const [error,setError]=useState('');const submit=e=>{e.preventDefault();if(!form.origin||!form.destination||!form.date||!form.time||!form.seats){setError('Please complete all required fields.');return}addRide(form);nav('/rides')};return <div className="container page narrow"><PageTitle eyebrow="SHARED RIDES" title="Offer a shared ride" subtitle="Publish a route so other RideRent customers can join your journey."/><form className="panel form" onSubmit={submit}><div className="form-grid"><label>Origin<input value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})} required/></label><label>Destination<input value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="e.g. Girona" required/></label><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label>Departure time<input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})} required/></label><label>Available seats<input type="number" min="1" max="8" value={form.seats} onChange={e=>setForm({...form,seats:e.target.value})} required/></label><label>Suggested contribution (€)<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label></div>{error&&<Alert type="error" text={error}/>}<div className="form-actions"><Link className="btn btn-ghost" to="/rides">Cancel</Link><button className="btn btn-primary">Publish ride <ArrowRight size={17}/></button></div></form><div className="scope-note"><ShieldCheck size={17}/><div><b>Good to know</b><span>RideRent Challenge 1 does not include real-time chat or dynamic pricing. This form publishes a simple shared-ride offer.</span></div></div></div>}
function LoginPage({onLogin}){const nav=useNavigate();const [email,setEmail]=useState('demo@riderent.app');const [password,setPassword]=useState('demo123');const [error,setError]=useState('');const submit=e=>{e.preventDefault();const x=onLogin(email,password);if(x.ok)nav('/');else setError(x.message)};return <AuthLayout eyebrow="WELCOME BACK" title="Log in to RideRent" subtitle="Access your bookings, rides and personal services."><form className="form" onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<Alert type="error" text={error}/>}<button className="btn btn-primary full">Log in <LogIn size={17}/></button><p className="form-note">Demo customer: demo@riderent.app / demo123<br/>Demo admin: admin@riderent.app / admin123</p></form><div className="auth-switch">New to RideRent? <Link to="/register">Create an account</Link></div></AuthLayout>}
function RegisterPage({onRegister}){const nav=useNavigate();const [form,setForm]=useState({name:'',email:'',password:''});const [error,setError]=useState('');const submit=e=>{e.preventDefault();const x=onRegister(form.name,form.email,form.password);if(x.ok)nav('/');else setError(x.message)};return <AuthLayout eyebrow="GET STARTED" title="Create your RideRent account" subtitle="One account for car rental and shared rides."><form className="form" onSubmit={submit}><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} autoComplete="name" required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} autoComplete="email" required/></label><label>Password<input type="password" minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} autoComplete="new-password" required/><small>Minimum 6 characters.</small></label>{error&&<Alert type="error" text={error}/>}<button className="btn btn-primary full">Create account <UserPlus size={17}/></button></form><div className="auth-switch">Already registered? <Link to="/login">Log in</Link></div></AuthLayout>}
function AuthLayout({eyebrow,title,subtitle,children}){return <div className="auth-page"><div className="auth-art"><Link className="brand" to="/"><span className="brand-mark"><CarFront size={20}/></span>Ride<span>Rent</span></Link><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div><div className="auth-art-bottom"><ShieldCheck size={18}/> Your personal booking area</div></div><div className="auth-box"><div className="auth-card">{children}</div></div></div>}
function AdminPage({cars,addCar,updateCar,toggleCar}){const [editing,setEditing]=useState(null);const [form,setForm]=useState({name:'',category:'Economy',seats:5,price:40,transmission:'Automatic',fuel:'Petrol',location:'Barcelona'});const reset=()=>{setEditing(null);setForm({name:'',category:'Economy',seats:5,price:40,transmission:'Automatic',fuel:'Petrol',location:'Barcelona'})};const submit=e=>{e.preventDefault();editing?updateCar(editing,form):addCar(form);reset()};return <div className="container page"><PageTitle eyebrow="ADMINISTRATION" title="Vehicle management" subtitle="Protected administrator area for maintaining the rental catalogue."/><div className="admin-grid"><section className="panel"><div className="panel-head"><div><b>{editing?'Edit vehicle':'Add vehicle'}</b><span>{editing?'Update the selected vehicle.':'Create a new catalogue vehicle.'}</span></div>{editing&&<button className="btn btn-ghost" onClick={reset}>Cancel</button>}</div><form className="form" onSubmit={submit}><label>Model<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><div className="form-grid"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Economy</option><option>Compact</option><option>SUV</option><option>Premium</option></select></label><label>Price / day<input type="number" min="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Seats<input type="number" min="1" max="9" value={form.seats} onChange={e=>setForm({...form,seats:e.target.value})}/></label><label>Transmission<select value={form.transmission} onChange={e=>setForm({...form,transmission:e.target.value})}><option>Automatic</option><option>Manual</option></select></label><label>Fuel<input value={form.fuel} onChange={e=>setForm({...form,fuel:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label></div><button className="btn btn-primary full">{editing?'Save changes':'Add vehicle'} <Plus size={17}/></button></form></section><section><div className="admin-list-head"><b>{cars.length} registered vehicles</b><span>Deactivate to prevent new reservations.</span></div><div className="admin-list">{cars.map(c=><div className="admin-row" key={c.id}><div><b>{c.name}</b><span>{c.category} · €{c.price}/day · {c.available?'Available':'Inactive'}</span></div><div className="row-actions"><button className="icon-btn" aria-label={'Edit '+c.name} onClick={()=>{setEditing(c.id);setForm(c)}}><Pencil size={16}/></button><button className="icon-btn" aria-label={'Toggle '+c.name} onClick={()=>toggleCar(c.id)}>{c.available?<Power size={16}/>:<CheckCircle2 size={16}/>}</button></div></div>)}</div></section></div></div>}
function PageTitle({eyebrow,title,subtitle}){return <div className="page-title"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>}
function Stat({n,label}){return <div className="stat"><strong>{n}</strong><span>{label}</span></div>}
function Empty({icon,title,text,action}){return <div className="empty">{icon}<h3>{title}</h3><p>{text}</p>{action}</div>}
function Alert({type,text}){return <div className={'alert '+type}>{type==='ok'?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>}<span>{text}</span></div>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
